name: 'Build'
description: 'Action for building a custom action'

inputs:
  command:
    description: 'Command to run inside the container'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
