on: [push]

jobs:
  install-modules:
    runs-on: ubuntu-22.04
    name: Installs modules
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dev dependencies
        uses: ./ 
        with:
          args: "pip3 install -r dev-requirements.txt"
