on: [push]

jobs:
  run-tests:
    name: Run Python Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r dev-requirements.txt

      - name: Run Tests
        run: pytest
